version: '3.3'    
services:
  cashflow:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9001:9001"
    environment:
      NODE_ENV: "production"
      LOG_LEVEL: "error"
      SERVER_PORT: "9001"
      ACCESS_TOKEN_SECRET: "1234"
    volumes:
      - ./../database.sqlite3:/usr/src/app/database.sqlite3